// <auto-generated />
namespace Pluto_Entity_In_Action.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class removeunnecessarytables2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeunnecessarytables2));
        
        string IMigrationMetadata.Id
        {
            get { return "201912091330189_removeunnecessarytables2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
